spring:
  profiles:
   active: dev
  mvc:
    view:
      prefix: /
      suffix: .html
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    cache: true
  freemarker:
    template-loader-path:
      classpath: /templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
